sudo: required
services:
    - docker

before_install:
    - docker build -t msmoreira/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true msmoreira/reac-test npm test

after_success:
    - docker build -t msmoreira/multi-client ./client 
    - docker build -t msmoreira/multi-nginx ./nginx
    - docker build -t msmoreira/multi-server ./server
    - docker build -t msmoreira/multi-worker ./worker 
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push msmoreira/multi-client
    - docker push msmoreira/multi-nginx
    - docker push msmoreira/multi-server
    - docker push msmoreira/multi-worker